packages:
  - native/*
onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
minimumReleaseAgeExclude:
  - '@ai-sdk/anthropic@4.0.3'
  - '@ai-sdk/deepseek@3.0.2'
  - '@ai-sdk/gateway@4.0.6'
  - '@ai-sdk/mcp@2.0.4'
  - '@ai-sdk/openai@4.0.4'
  - '@ai-sdk/provider-utils@5.0.2'
  - '@ai-sdk/provider@4.0.1'
  - '@ai-sdk/react@4.0.9'
  - ai@7.0.8
  - '@ai-sdk/devtools@1.0.1'
