/**
 * Tool preview shapes — what the approval card renders before a
 * destructive tool runs. Generated by main-process preview generators
 * (see `./index.ts`) during the approval phase, transported as plain
 * JSON via the `ai:stream-tool-batch-approval` IPC payload, and
 * consumed by renderer preview cards.
 *
 * All shapes must stay JSON-serializable: no functions, classes, Dates,
 * or buffers. IPC bridges and JSONL persistence both rely on this.
 */

export interface PreviewDiffHunk {
  kind: "added" | "removed" | "context";
  /**
   * The raw change text including its trailing newline, matching the
   * `Change.value` shape from the `diff` npm package's `diffLines()`.
   */
  value: string;
  lineCount: number;
}

export interface WriteFilePreview {
  kind: "write";
  path: string;
  action: "create" | "overwrite";
  oldExists: boolean;
  isBinary: boolean;
  oldLines: number;
  newLines: number;
  added: number;
  removed: number;
  /** Empty when binary or truncated. */
  hunks: PreviewDiffHunk[];
  truncated?: "oldTooLarge" | "newTooLarge" | "diffTooLarge";
  /** sha1(oldRaw) — lets the executor detect external modifications between approval and apply. */
  oldHash?: string;
}

export interface MoveFilePreview {
  kind: "move";
  source: string;
  destination: string;
  sourceExists: boolean;
  sourceType: "file" | "dir" | "unknown";
  destinationExists: boolean;
}

export interface DeleteFilePreview {
  kind: "delete";
  path: string;
  exists: boolean;
  type: "file" | "dir" | "unknown";
  sizeBytes?: number;
  /** Directory only. Capped at 5000 — anything above renders as "5000+". */
  childCount?: number;
  /** Text files only: first ≤20 lines, total ≤2 KB. */
  headPreview?: string[];
}

export interface CreateDirectoryPreview {
  kind: "mkdir";
  path: string;
  alreadyExists: boolean;
  parentExists: boolean;
}

export interface RunCommandPreview {
  kind: "run";
  command: string;
  cwd?: string;
  cwdExists: boolean;
}

export type ToolPreview =
  | WriteFilePreview
  | MoveFilePreview
  | DeleteFilePreview
  | CreateDirectoryPreview
  | RunCommandPreview;
