// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "en" | "ja" | "zh-CN";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * F​i​l​e​W​o​r​k
   */
  appName: string;
  /**
   * Y​o​u​r​ ​L​o​c​a​l​ ​F​i​l​e​ ​A​I​ ​A​s​s​i​s​t​a​n​t
   */
  tagline: string;
  /**
   * F​i​l​e​W​o​r​k
   */
  welcome_title: string;
  /**
   * Y​o​u​r​ ​l​o​c​a​l​ ​f​i​l​e​ ​A​I​ ​a​s​s​i​s​t​a​n​t​.​ ​S​e​l​e​c​t​ ​a​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​t​e​l​l​ ​m​e​ ​w​h​a​t​ ​t​o​ ​d​o​.
   */
  welcome_description: string;
  /**
   * S​e​l​e​c​t​ ​W​o​r​k​i​n​g​ ​D​i​r​e​c​t​o​r​y
   */
  welcome_selectDirectory: string;
  /**
   * F​i​l​e​W​o​r​k​ ​o​n​l​y​ ​w​o​r​k​s​ ​w​i​t​h​i​n​ ​y​o​u​r​ ​s​e​l​e​c​t​e​d​ ​d​i​r​e​c​t​o​r​y​.​ ​Y​o​u​r​ ​d​a​t​a​ ​n​e​v​e​r​ ​l​e​a​v​e​s​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r​.
   */
  welcome_privacy: string;
  /**
   * T​e​l​l​ ​m​e​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​.​.​.​ ​(​⌘​+​E​n​t​e​r​ ​t​o​ ​s​e​n​d​)
   */
  chat_placeholder: string;
  /**
   * H​o​w​ ​c​a​n​ ​I​ ​h​e​l​p​?
   */
  chat_emptyTitle: string;
  /**
   * T​e​l​l​ ​m​e​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​ ​w​i​t​h​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y
   */
  chat_emptyDescription: string;
  /**
   * O​r​g​a​n​i​z​e​ ​f​i​l​e​s​ ​i​n​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​ ​b​y​ ​t​y​p​e
   */
  suggestion_organize: string;
  /**
   * A​n​a​l​y​z​e​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​g​e​n​e​r​a​t​e​ ​a​ ​r​e​p​o​r​t
   */
  suggestion_report: string;
  /**
   * F​i​n​d​ ​a​l​l​ ​d​u​p​l​i​c​a​t​e​ ​f​i​l​e​s
   */
  suggestion_duplicates: string;
  /**
   * C​o​u​n​t​ ​f​i​l​e​s​ ​b​y​ ​t​y​p​e​ ​a​n​d​ ​s​i​z​e
   */
  suggestion_stats: string;
  /**
   * S​e​t​t​i​n​g​s
   */
  sidebar_settings: string;
  /**
   * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
   */
  sidebar_collapse: string;
  /**
   * S​e​t​t​i​n​g​s
   */
  settings_title: string;
  /**
   * A​I​ ​P​r​o​v​i​d​e​r
   */
  settings_aiProvider: string;
  /**
   * A​P​I​ ​K​e​y
   */
  settings_apiKey: string;
  /**
   * M​o​d​e​l
   */
  settings_model: string;
  /**
   * L​a​n​g​u​a​g​e
   */
  settings_language: string;
  /**
   * T​h​e​m​e
   */
  settings_theme: string;
  /**
   * D​a​r​k
   */
  settings_themeDark: string;
  /**
   * L​i​g​h​t
   */
  settings_themeLight: string;
  /**
   * S​y​s​t​e​m
   */
  settings_themeSystem: string;
  /**
   * T​e​s​t​ ​C​o​n​n​e​c​t​i​o​n
   */
  settings_testConnection: string;
  /**
   * P​e​n​d​i​n​g
   */
  task_pending: string;
  /**
   * R​u​n​n​i​n​g
   */
  task_running: string;
  /**
   * C​o​m​p​l​e​t​e​d
   */
  task_completed: string;
  /**
   * F​a​i​l​e​d
   */
  task_failed: string;
  /**
   * U​n​d​o
   */
  task_undo: string;
  /**
   * L​L​M​ ​C​h​a​n​n​e​l​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
   */
  llmConfig_title: string;
  /**
   * A​d​d​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
   */
  llmConfig_add: string;
  /**
   * E​d​i​t
   */
  llmConfig_edit: string;
  /**
   * D​e​l​e​t​e
   */
  llmConfig_delete: string;
  /**
   * D​i​s​p​l​a​y​ ​N​a​m​e
   */
  llmConfig_name: string;
  /**
   * P​r​o​v​i​d​e​r
   */
  llmConfig_provider: string;
  /**
   * A​P​I​ ​K​e​y
   */
  llmConfig_apiKey: string;
  /**
   * B​a​s​e​ ​U​R​L
   */
  llmConfig_baseUrl: string;
  /**
   * M​o​d​e​l
   */
  llmConfig_model: string;
  /**
   * D​e​f​a​u​l​t
   */
  llmConfig_default: string;
  /**
   * S​e​t​ ​a​s​ ​D​e​f​a​u​l​t
   */
  llmConfig_setDefault: string;
  /**
   * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​?
   */
  llmConfig_deleteConfirm: string;
  /**
   * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​d​e​f​a​u​l​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​m​u​s​t​ ​b​e​ ​k​e​p​t
   */
  llmConfig_deleteLastError: string;
  /**
   * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
   */
  llmConfig_validationRequired: string;
  /**
   * A​P​I​ ​K​e​y​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​t​h​e​ ​c​h​a​n​n​e​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​i​n​ ​s​e​t​t​i​n​g​s
   */
  llmConfig_authError: string;
  /**
   * S​e​l​e​c​t​e​d​ ​L​L​M​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
   */
  llmConfig_notFound: string;
  /**
   * S​a​v​e
   */
  llmConfig_save: string;
  /**
   * C​a​n​c​e​l
   */
  llmConfig_cancel: string;
  /**
   * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
   */
  error_unknown: string;
  /**
   * F​a​i​l​e​d​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​A​I​ ​p​r​o​v​i​d​e​r
   */
  error_aiConnection: string;
  /**
   * C​a​n​n​o​t​ ​a​c​c​e​s​s​ ​f​i​l​e​ ​o​r​ ​d​i​r​e​c​t​o​r​y
   */
  error_fileAccess: string;
};

export type TranslationFunctions = {
  /**
   * FileWork
   */
  appName: () => LocalizedString;
  /**
   * Your Local File AI Assistant
   */
  tagline: () => LocalizedString;
  /**
   * FileWork
   */
  welcome_title: () => LocalizedString;
  /**
   * Your local file AI assistant. Select a working directory and tell me what to do.
   */
  welcome_description: () => LocalizedString;
  /**
   * Select Working Directory
   */
  welcome_selectDirectory: () => LocalizedString;
  /**
   * FileWork only works within your selected directory. Your data never leaves your computer.
   */
  welcome_privacy: () => LocalizedString;
  /**
   * Tell me what you want to do... (⌘+Enter to send)
   */
  chat_placeholder: () => LocalizedString;
  /**
   * How can I help?
   */
  chat_emptyTitle: () => LocalizedString;
  /**
   * Tell me what you want to do with this directory
   */
  chat_emptyDescription: () => LocalizedString;
  /**
   * Organize files in this directory by type
   */
  suggestion_organize: () => LocalizedString;
  /**
   * Analyze this directory and generate a report
   */
  suggestion_report: () => LocalizedString;
  /**
   * Find all duplicate files
   */
  suggestion_duplicates: () => LocalizedString;
  /**
   * Count files by type and size
   */
  suggestion_stats: () => LocalizedString;
  /**
   * Settings
   */
  sidebar_settings: () => LocalizedString;
  /**
   * Collapse sidebar
   */
  sidebar_collapse: () => LocalizedString;
  /**
   * Settings
   */
  settings_title: () => LocalizedString;
  /**
   * AI Provider
   */
  settings_aiProvider: () => LocalizedString;
  /**
   * API Key
   */
  settings_apiKey: () => LocalizedString;
  /**
   * Model
   */
  settings_model: () => LocalizedString;
  /**
   * Language
   */
  settings_language: () => LocalizedString;
  /**
   * Theme
   */
  settings_theme: () => LocalizedString;
  /**
   * Dark
   */
  settings_themeDark: () => LocalizedString;
  /**
   * Light
   */
  settings_themeLight: () => LocalizedString;
  /**
   * System
   */
  settings_themeSystem: () => LocalizedString;
  /**
   * Test Connection
   */
  settings_testConnection: () => LocalizedString;
  /**
   * Pending
   */
  task_pending: () => LocalizedString;
  /**
   * Running
   */
  task_running: () => LocalizedString;
  /**
   * Completed
   */
  task_completed: () => LocalizedString;
  /**
   * Failed
   */
  task_failed: () => LocalizedString;
  /**
   * Undo
   */
  task_undo: () => LocalizedString;
  /**
   * LLM Channel Configuration
   */
  llmConfig_title: () => LocalizedString;
  /**
   * Add Configuration
   */
  llmConfig_add: () => LocalizedString;
  /**
   * Edit
   */
  llmConfig_edit: () => LocalizedString;
  /**
   * Delete
   */
  llmConfig_delete: () => LocalizedString;
  /**
   * Display Name
   */
  llmConfig_name: () => LocalizedString;
  /**
   * Provider
   */
  llmConfig_provider: () => LocalizedString;
  /**
   * API Key
   */
  llmConfig_apiKey: () => LocalizedString;
  /**
   * Base URL
   */
  llmConfig_baseUrl: () => LocalizedString;
  /**
   * Model
   */
  llmConfig_model: () => LocalizedString;
  /**
   * Default
   */
  llmConfig_default: () => LocalizedString;
  /**
   * Set as Default
   */
  llmConfig_setDefault: () => LocalizedString;
  /**
   * Are you sure you want to delete this configuration?
   */
  llmConfig_deleteConfirm: () => LocalizedString;
  /**
   * At least one default configuration must be kept
   */
  llmConfig_deleteLastError: () => LocalizedString;
  /**
   * This field is required
   */
  llmConfig_validationRequired: () => LocalizedString;
  /**
   * API Key is invalid or expired, please check the channel configuration in settings
   */
  llmConfig_authError: () => LocalizedString;
  /**
   * Selected LLM configuration does not exist
   */
  llmConfig_notFound: () => LocalizedString;
  /**
   * Save
   */
  llmConfig_save: () => LocalizedString;
  /**
   * Cancel
   */
  llmConfig_cancel: () => LocalizedString;
  /**
   * An unknown error occurred
   */
  error_unknown: () => LocalizedString;
  /**
   * Failed to connect to AI provider
   */
  error_aiConnection: () => LocalizedString;
  /**
   * Cannot access file or directory
   */
  error_fileAccess: () => LocalizedString;
};

export type Formatters = {};
