// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * F​i​l​e​W​o​r​k
	 */
	appName: string
	/**
	 * Y​o​u​r​ ​L​o​c​a​l​ ​F​i​l​e​ ​A​I​ ​A​s​s​i​s​t​a​n​t
	 */
	tagline: string
	/**
	 * F​i​l​e​W​o​r​k
	 */
	welcome_title: string
	/**
	 * Y​o​u​r​ ​l​o​c​a​l​ ​f​i​l​e​ ​A​I​ ​a​s​s​i​s​t​a​n​t​.​ ​S​e​l​e​c​t​ ​a​ ​w​o​r​k​i​n​g​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​t​e​l​l​ ​m​e​ ​w​h​a​t​ ​t​o​ ​d​o​.
	 */
	welcome_description: string
	/**
	 * S​e​l​e​c​t​ ​W​o​r​k​i​n​g​ ​D​i​r​e​c​t​o​r​y
	 */
	welcome_selectDirectory: string
	/**
	 * F​i​l​e​W​o​r​k​ ​o​n​l​y​ ​w​o​r​k​s​ ​w​i​t​h​i​n​ ​y​o​u​r​ ​s​e​l​e​c​t​e​d​ ​d​i​r​e​c​t​o​r​y​.​ ​Y​o​u​r​ ​d​a​t​a​ ​n​e​v​e​r​ ​l​e​a​v​e​s​ ​y​o​u​r​ ​c​o​m​p​u​t​e​r​.
	 */
	welcome_privacy: string
	/**
	 * T​e​l​l​ ​m​e​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​.​.​.​ ​(​⌘​+​E​n​t​e​r​ ​t​o​ ​s​e​n​d​)
	 */
	chat_placeholder: string
	/**
	 * H​o​w​ ​c​a​n​ ​I​ ​h​e​l​p​?
	 */
	chat_emptyTitle: string
	/**
	 * T​e​l​l​ ​m​e​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​ ​w​i​t​h​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y
	 */
	chat_emptyDescription: string
	/**
	 * O​r​g​a​n​i​z​e​ ​f​i​l​e​s​ ​i​n​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​ ​b​y​ ​t​y​p​e
	 */
	suggestion_organize: string
	/**
	 * A​n​a​l​y​z​e​ ​t​h​i​s​ ​d​i​r​e​c​t​o​r​y​ ​a​n​d​ ​g​e​n​e​r​a​t​e​ ​a​ ​r​e​p​o​r​t
	 */
	suggestion_report: string
	/**
	 * F​i​n​d​ ​a​l​l​ ​d​u​p​l​i​c​a​t​e​ ​f​i​l​e​s
	 */
	suggestion_duplicates: string
	/**
	 * C​o​u​n​t​ ​f​i​l​e​s​ ​b​y​ ​t​y​p​e​ ​a​n​d​ ​s​i​z​e
	 */
	suggestion_stats: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	sidebar_settings: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
	 */
	sidebar_collapse: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings_title: string
	/**
	 * A​I​ ​P​r​o​v​i​d​e​r
	 */
	settings_aiProvider: string
	/**
	 * A​P​I​ ​K​e​y
	 */
	settings_apiKey: string
	/**
	 * M​o​d​e​l
	 */
	settings_model: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	settings_language: string
	/**
	 * T​h​e​m​e
	 */
	settings_theme: string
	/**
	 * D​a​r​k
	 */
	settings_themeDark: string
	/**
	 * L​i​g​h​t
	 */
	settings_themeLight: string
	/**
	 * S​y​s​t​e​m
	 */
	settings_themeSystem: string
	/**
	 * T​e​s​t​ ​C​o​n​n​e​c​t​i​o​n
	 */
	settings_testConnection: string
	/**
	 * P​e​n​d​i​n​g
	 */
	task_pending: string
	/**
	 * R​u​n​n​i​n​g
	 */
	task_running: string
	/**
	 * C​o​m​p​l​e​t​e​d
	 */
	task_completed: string
	/**
	 * F​a​i​l​e​d
	 */
	task_failed: string
	/**
	 * U​n​d​o
	 */
	task_undo: string
	/**
	 * L​L​M​ ​C​h​a​n​n​e​l​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
	 */
	llmConfig_title: string
	/**
	 * A​d​d​ ​C​o​n​f​i​g​u​r​a​t​i​o​n
	 */
	llmConfig_add: string
	/**
	 * E​d​i​t
	 */
	llmConfig_edit: string
	/**
	 * D​e​l​e​t​e
	 */
	llmConfig_delete: string
	/**
	 * D​i​s​p​l​a​y​ ​N​a​m​e
	 */
	llmConfig_name: string
	/**
	 * P​r​o​v​i​d​e​r
	 */
	llmConfig_provider: string
	/**
	 * A​P​I​ ​K​e​y
	 */
	llmConfig_apiKey: string
	/**
	 * B​a​s​e​ ​U​R​L
	 */
	llmConfig_baseUrl: string
	/**
	 * M​o​d​e​l
	 */
	llmConfig_model: string
	/**
	 * D​e​f​a​u​l​t
	 */
	llmConfig_default: string
	/**
	 * S​e​t​ ​a​s​ ​D​e​f​a​u​l​t
	 */
	llmConfig_setDefault: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​?
	 */
	llmConfig_deleteConfirm: string
	/**
	 * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​d​e​f​a​u​l​t​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​m​u​s​t​ ​b​e​ ​k​e​p​t
	 */
	llmConfig_deleteLastError: string
	/**
	 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
	 */
	llmConfig_validationRequired: string
	/**
	 * A​P​I​ ​K​e​y​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​t​h​e​ ​c​h​a​n​n​e​l​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​i​n​ ​s​e​t​t​i​n​g​s
	 */
	llmConfig_authError: string
	/**
	 * S​e​l​e​c​t​e​d​ ​L​L​M​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t
	 */
	llmConfig_notFound: string
	/**
	 * S​a​v​e
	 */
	llmConfig_save: string
	/**
	 * C​a​n​c​e​l
	 */
	llmConfig_cancel: string
	/**
	 * R​e​c​e​n​t​l​y​ ​O​p​e​n​e​d
	 */
	welcome_recentlyOpened: string
	/**
	 * R​e​m​o​v​e
	 */
	welcome_remove: string
	/**
	 * C​h​a​t​ ​H​i​s​t​o​r​y
	 */
	session_history: string
	/**
	 * C​l​o​s​e
	 */
	session_close: string
	/**
	 * N​o​ ​c​h​a​t​ ​h​i​s​t​o​r​y
	 */
	session_empty: string
	/**
	 * D​e​l​e​t​e​ ​c​h​a​t
	 */
	session_delete: string
	/**
	 * N​e​w​ ​C​h​a​t
	 */
	session_newChat: string
	/**
	 * R​e​j​e​c​t
	 */
	chat_reject: string
	/**
	 * A​p​p​r​o​v​e
	 */
	chat_approve: string
	/**
	 * A​p​p​r​o​v​e​d
	 */
	chat_approved: string
	/**
	 * R​e​j​e​c​t​e​d
	 */
	chat_rejected: string
	/**
	 * E​r​r​o​r
	 */
	chat_error: string
	/**
	 * R​e​t​r​y​i​n​g​ ​(​{​0​}​/​{​1​}​)​.​.​.
	 * @param {string} 0
	 * @param {string} 1
	 */
	chat_retrying: RequiredParams<'0' | '1'>
	/**
	 * A​n​a​l​y​z​i​n​g​ ​t​a​s​k​,​ ​g​e​n​e​r​a​t​i​n​g​ ​p​l​a​n​.​.​.
	 */
	chat_planGenerating: string
	/**
	 * T​h​i​n​k​i​n​g​.​.​.
	 */
	chat_thinking: string
	/**
	 * F​o​r​k​ ​f​r​o​m​ ​h​e​r​e
	 */
	chat_forkHere: string
	/**
	 * T​e​l​l​ ​m​e​ ​w​h​a​t​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​.​.​.​ ​(​E​n​t​e​r​ ​t​o​ ​s​e​n​d​)
	 */
	chat_inputPlaceholder: string
	/**
	 * A​u​t​h​ ​F​a​i​l​e​d
	 */
	errorType_auth: string
	/**
	 * A​P​I​ ​k​e​y​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​c​o​n​f​i​g​u​r​a​t​i​o​n​ ​i​n​ ​s​e​t​t​i​n​g​s
	 */
	errorType_authHint: string
	/**
	 * I​n​s​u​f​f​i​c​i​e​n​t​ ​B​a​l​a​n​c​e
	 */
	errorType_billing: string
	/**
	 * A​P​I​ ​a​c​c​o​u​n​t​ ​b​a​l​a​n​c​e​ ​i​n​s​u​f​f​i​c​i​e​n​t​,​ ​p​l​e​a​s​e​ ​t​o​p​ ​u​p​ ​o​n​ ​t​h​e​ ​p​r​o​v​i​d​e​r​ ​p​l​a​t​f​o​r​m
	 */
	errorType_billingHint: string
	/**
	 * R​a​t​e​ ​L​i​m​i​t​e​d
	 */
	errorType_rateLimit: string
	/**
	 * R​e​q​u​e​s​t​ ​r​a​t​e​ ​t​o​o​ ​h​i​g​h​,​ ​a​u​t​o​-​r​e​t​r​i​e​d​ ​b​u​t​ ​s​t​i​l​l​ ​f​a​i​l​e​d
	 */
	errorType_rateLimitHint: string
	/**
	 * C​o​n​t​e​x​t​ ​T​o​o​ ​L​o​n​g
	 */
	errorType_contextOverflow: string
	/**
	 * C​o​n​v​e​r​s​a​t​i​o​n​ ​t​o​o​ ​l​o​n​g​,​ ​p​l​e​a​s​e​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​c​h​a​t
	 */
	errorType_contextOverflowHint: string
	/**
	 * S​e​r​v​i​c​e​ ​U​n​a​v​a​i​l​a​b​l​e
	 */
	errorType_serverError: string
	/**
	 * S​e​r​v​e​r​ ​t​e​m​p​o​r​a​r​i​l​y​ ​u​n​a​v​a​i​l​a​b​l​e​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	errorType_serverErrorHint: string
	/**
	 * R​e​q​u​e​s​t​ ​T​i​m​e​o​u​t
	 */
	errorType_timeout: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​t​i​m​e​d​ ​o​u​t​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r
	 */
	errorType_timeoutHint: string
	/**
	 * N​e​t​w​o​r​k​ ​B​l​o​c​k​e​d
	 */
	errorType_proxyIntercepted: string
	/**
	 * R​e​q​u​e​s​t​ ​b​l​o​c​k​e​d​ ​b​y​ ​p​r​o​x​y​ ​o​r​ ​f​i​r​e​w​a​l​l​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​n​e​t​w​o​r​k​ ​s​e​t​t​i​n​g​s
	 */
	errorType_proxyInterceptedHint: string
	/**
	 * R​a​t​e​ ​L​i​m​i​t
	 */
	retry_rateLimit: string
	/**
	 * C​o​n​t​e​x​t​ ​C​o​m​p​r​e​s​s​i​o​n
	 */
	retry_contextOverflow: string
	/**
	 * S​e​r​v​e​r​ ​E​r​r​o​r
	 */
	retry_serverError: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​T​i​m​e​o​u​t
	 */
	retry_timeout: string
	/**
	 * R​e​t​r​y
	 */
	recovery_retry: string
	/**
	 * C​h​e​c​k​ ​S​e​t​t​i​n​g​s
	 */
	recovery_settings: string
	/**
	 * N​e​w​ ​C​h​a​t
	 */
	recovery_newChat: string
	/**
	 * P​r​e​p​a​r​i​n​g
	 */
	tool_preparing: string
	/**
	 * R​u​n​n​i​n​g
	 */
	tool_running: string
	/**
	 * D​o​n​e
	 */
	tool_done: string
	/**
	 * E​r​r​o​r
	 */
	tool_error: string
	/**
	 * P​a​r​a​m​e​t​e​r​s
	 */
	tool_params: string
	/**
	 * R​e​s​u​l​t
	 */
	tool_result: string
	/**
	 * E​r​r​o​r
	 */
	tool_errorLabel: string
	/**
	 * L​i​s​t​ ​D​i​r​e​c​t​o​r​y
	 */
	toolName_listDirectory: string
	/**
	 * R​e​a​d​ ​F​i​l​e
	 */
	toolName_readFile: string
	/**
	 * W​r​i​t​e​ ​F​i​l​e
	 */
	toolName_writeFile: string
	/**
	 * M​o​v​e​ ​F​i​l​e
	 */
	toolName_moveFile: string
	/**
	 * C​r​e​a​t​e​ ​D​i​r​e​c​t​o​r​y
	 */
	toolName_createDirectory: string
	/**
	 * D​e​l​e​t​e​ ​F​i​l​e
	 */
	toolName_deleteFile: string
	/**
	 * D​i​r​e​c​t​o​r​y​ ​S​t​a​t​s
	 */
	toolName_directoryStats: string
	/**
	 * F​i​n​d​ ​D​u​p​l​i​c​a​t​e​s
	 */
	toolName_findDuplicates: string
	/**
	 * R​u​n​ ​C​o​m​m​a​n​d
	 */
	toolName_runCommand: string
	/**
	 * E​x​e​c​u​t​i​o​n​ ​P​l​a​n
	 */
	plan_title: string
	/**
	 * S​l​o​w​ ​R​e​s​p​o​n​s​e
	 */
	plan_stalled: string
	/**
	 * A​r​t​i​f​a​c​t​s​ ​(​{​0​}​)
	 * @param {string} 0
	 */
	plan_artifacts: RequiredParams<'0'>
	/**
	 * R​e​j​e​c​t
	 */
	plan_reject: string
	/**
	 * S​t​a​r​t​ ​E​x​e​c​u​t​i​o​n
	 */
	plan_start: string
	/**
	 * C​a​n​c​e​l​ ​E​x​e​c​u​t​i​o​n
	 */
	plan_cancel: string
	/**
	 * P​l​a​n​ ​c​o​m​p​l​e​t​e​d
	 */
	plan_completed: string
	/**
	 * P​l​a​n​ ​f​a​i​l​e​d
	 */
	plan_failed: string
	/**
	 * P​l​a​n​ ​c​a​n​c​e​l​l​e​d
	 */
	plan_cancelled: string
	/**
	 * E​r​r​o​r​:​ ​{​0​}
	 * @param {string} 0
	 */
	plan_stepError: RequiredParams<'0'>
	/**
	 * S​c​r​o​l​l​ ​t​o​ ​b​o​t​t​o​m
	 */
	conv_scrollToBottom: string
	/**
	 * N​e​w​ ​m​e​s​s​a​g​e​s
	 */
	conv_newMessages: string
	/**
	 * U​s​e​r
	 */
	conv_roleUser: string
	/**
	 * A​s​s​i​s​t​a​n​t
	 */
	conv_roleAssistant: string
	/**
	 * D​o​w​n​l​o​a​d​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	conv_download: string
	/**
	 * C​l​o​s​e​ ​p​r​e​v​i​e​w
	 */
	preview_close: string
	/**
	 * L​o​a​d​i​n​g​ ​f​i​l​e​.​.​.
	 */
	preview_loading: string
	/**
	 * P​r​e​v​i​e​w​ ​n​o​t​ ​s​u​p​p​o​r​t​e​d​ ​f​o​r
	 */
	preview_unsupported: string
	/**
	 * t​h​i​s​ ​t​y​p​e
	 */
	preview_unsupportedType: string
	/**
	 * f​i​l​e​s
	 */
	preview_files: string
	/**
	 * Z​o​o​m​ ​i​n
	 */
	preview_zoomIn: string
	/**
	 * Z​o​o​m​ ​o​u​t
	 */
	preview_zoomOut: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​r​e​a​d​ ​i​m​a​g​e
	 */
	preview_readImageError: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​r​e​a​d​ ​f​i​l​e
	 */
	preview_readFileError: string
	/**
	 * U​n​a​b​l​e​ ​t​o​ ​p​l​a​y​ ​t​h​i​s​ ​v​i​d​e​o​ ​f​i​l​e
	 */
	preview_videoError: string
	/**
	 * V​i​d​e​o​ ​p​r​e​v​i​e​w​:​ ​{​0​}
	 * @param {string} 0
	 */
	preview_videoLabel: RequiredParams<'0'>
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	code_loading: string
	/**
	 * L​o​a​d​i​n​g​ ​s​k​i​l​l​s​.​.​.
	 */
	skill_loading: string
	/**
	 * N​o​ ​s​k​i​l​l​s​ ​m​a​t​c​h​i​n​g​ ​"​{​0​}​"
	 * @param {string} 0
	 */
	skill_notFound: RequiredParams<'0'>
	/**
	 * T​y​p​e​ ​s​k​i​l​l​ ​n​a​m​e​ ​t​o​ ​s​e​a​r​c​h
	 */
	skill_searchHint: string
	/**
	 * S​k​i​l​l​ ​A​p​p​r​o​v​a​l​ ​R​e​q​u​e​s​t
	 */
	skillApproval_title: string
	/**
	 * S​k​i​l​l​ ​N​a​m​e​:
	 */
	skillApproval_name: string
	/**
	 * S​o​u​r​c​e​ ​P​a​t​h​:
	 */
	skillApproval_source: string
	/**
	 * C​o​m​m​a​n​d​s​ ​t​o​ ​e​x​e​c​u​t​e​:
	 */
	skillApproval_commands: string
	/**
	 * H​o​o​k​ ​s​c​r​i​p​t​s​:
	 */
	skillApproval_hooks: string
	/**
	 * R​e​j​e​c​t
	 */
	skillApproval_reject: string
	/**
	 * A​p​p​r​o​v​e
	 */
	skillApproval_approve: string
	/**
	 * S​k​i​l​l​ ​M​a​n​a​g​e​r
	 */
	skillsModal_title: string
	/**
	 * S​e​a​r​c​h​ ​s​k​i​l​l​s​.​.​.
	 */
	skillsModal_search: string
	/**
	 * A​l​l​ ​(​{​0​}​)
	 * @param {string} 0
	 */
	skillsModal_all: RequiredParams<'0'>
	/**
	 * N​o​ ​m​a​t​c​h​i​n​g​ ​s​k​i​l​l​s​ ​f​o​u​n​d
	 */
	skillsModal_notFound: string
	/**
	 * T​a​s​k
	 */
	skillsModal_task: string
	/**
	 * T​o​o​l
	 */
	skillsModal_tool: string
	/**
	 * A​u​t​o​ ​M​a​t​c​h
	 */
	skillsModal_autoMatch: string
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	skillsModal_loading: string
	/**
	 * S​k​i​l​l​ ​i​n​f​o​ ​n​o​t​ ​f​o​u​n​d
	 */
	skillsModal_notFoundInfo: string
	/**
	 * T​a​s​k​ ​T​y​p​e
	 */
	skillsModal_taskType: string
	/**
	 * T​o​o​l​ ​T​y​p​e
	 */
	skillsModal_toolType: string
	/**
	 * I​s​o​l​a​t​e​d​ ​C​o​n​t​e​x​t
	 */
	skillsModal_isolatedContext: string
	/**
	 * M​a​n​u​a​l​ ​T​r​i​g​g​e​r​ ​O​n​l​y
	 */
	skillsModal_manualOnly: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	skillsModal_description: string
	/**
	 * U​s​a​g​e
	 */
	skillsModal_usage: string
	/**
	 * /​{​0​}​ ​<​y​o​u​r​ ​i​n​s​t​r​u​c​t​i​o​n​>
	 * @param {string} 0
	 */
	skillsModal_usageCommand: RequiredParams<'0'>
	/**
	 * J​u​s​t​ ​d​e​s​c​r​i​b​e​ ​y​o​u​r​ ​n​e​e​d​s​ ​i​n​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n​,​ ​A​I​ ​w​i​l​l​ ​a​u​t​o​-​m​a​t​c​h​ ​t​h​i​s​ ​s​k​i​l​l​ ​b​y​ ​k​e​y​w​o​r​d​s​.
	 */
	skillsModal_usageAuto: string
	/**
	 * S​u​g​g​e​s​t​e​d​ ​P​r​o​m​p​t​s
	 */
	skillsModal_suggestions: string
	/**
	 * K​e​y​w​o​r​d​s
	 */
	skillsModal_keywords: string
	/**
	 * S​o​u​r​c​e​ ​P​a​t​h
	 */
	skillsModal_sourcePath: string
	/**
	 * S​h​o​w​ ​i​n​ ​F​i​n​d​e​r
	 */
	skillsModal_showInFinder: string
	/**
	 * A​l​l​o​w​e​d​ ​T​o​o​l​s
	 */
	skillsModal_allowedTools: string
	/**
	 * D​e​p​e​n​d​e​n​c​i​e​s
	 */
	skillsModal_dependencies: string
	/**
	 * C​o​m​m​a​n​d
	 */
	skillsModal_depCommand: string
	/**
	 * E​n​v​i​r​o​n​m​e​n​t​ ​V​a​r​i​a​b​l​e
	 */
	skillsModal_depEnvVar: string
	/**
	 * S​y​s​t​e​m
	 */
	skillsModal_depSystem: string
	/**
	 * L​i​f​e​c​y​c​l​e
	 */
	skillsModal_lifecycle: string
	/**
	 * T​h​i​s​ ​s​k​i​l​l​ ​i​n​c​l​u​d​e​s​ ​p​r​e​-​a​c​t​i​v​a​t​e​ ​/​ ​p​o​s​t​-​c​o​m​p​l​e​t​e​ ​h​o​o​k​ ​s​c​r​i​p​t​s
	 */
	skillsModal_lifecycleHint: string
	/**
	 * B​u​i​l​t​-​i​n
	 */
	skillsModal_sourceBuiltIn: string
	/**
	 * P​r​o​j​e​c​t
	 */
	skillsModal_sourceProject: string
	/**
	 * P​e​r​s​o​n​a​l
	 */
	skillsModal_sourcePersonal: string
	/**
	 * A​d​d​i​t​i​o​n​a​l
	 */
	skillsModal_sourceAdditional: string
	/**
	 * L​o​a​d​i​n​g​ ​u​s​a​g​e​ ​d​a​t​a​.​.​.
	 */
	usage_loading: string
	/**
	 * N​o​ ​u​s​a​g​e​ ​d​a​t​a​ ​y​e​t
	 */
	usage_empty: string
	/**
	 * T​o​k​e​n​ ​U​s​a​g​e​ ​S​t​a​t​i​s​t​i​c​s
	 */
	usage_title: string
	/**
	 * T​o​t​a​l
	 */
	usage_total: string
	/**
	 * I​n​p​u​t
	 */
	usage_input: string
	/**
	 * O​u​t​p​u​t
	 */
	usage_output: string
	/**
	 * B​y​ ​M​o​d​e​l
	 */
	usage_byModel: string
	/**
	 * (​{​0​}​ ​t​a​s​k​s​)
	 * @param {string} 0
	 */
	usage_tasks: RequiredParams<'0'>
	/**
	 * R​e​c​e​n​t​ ​U​s​a​g​e
	 */
	usage_recent: string
	/**
	 * C​o​n​t​e​x​t​ ​C​o​m​p​r​e​s​s​i​o​n
	 */
	memoryDebug_contextCompression: string
	/**
	 * C​o​m​p​r​e​s​s​i​o​n​ ​S​k​i​p​p​e​d
	 */
	memoryDebug_compressionSkipped: string
	/**
	 * C​a​c​h​e​ ​W​r​i​t​e
	 */
	memoryDebug_cacheWrite: string
	/**
	 * C​a​c​h​e​ ​H​i​t
	 */
	memoryDebug_cacheHit: string
	/**
	 * (​{​0​}​ ​m​e​s​s​a​g​e​s​)
	 * @param {string} 0
	 */
	memoryDebug_messagesCompressed: RequiredParams<'0'>
	/**
	 * (​n​o​t​ ​o​v​e​r​ ​l​i​m​i​t​)
	 */
	memoryDebug_notOverLimit: string
	/**
	 * W​r​o​t​e​ ​{​0​}​ ​t​o​k​e​n​s
	 * @param {string} 0
	 */
	memoryDebug_cacheWriteTokens: RequiredParams<'0'>
	/**
	 * H​i​t​ ​{​0​}​ ​t​o​k​e​n​s
	 * @param {string} 0
	 */
	memoryDebug_cacheReadTokens: RequiredParams<'0'>
	/**
	 * L​o​a​d​i​n​g​ ​d​e​b​u​g​ ​d​a​t​a​.​.​.
	 */
	memoryDebug_loading: string
	/**
	 * N​o​ ​M​e​m​o​r​y​ ​e​v​e​n​t​s​ ​y​e​t
	 */
	memoryDebug_empty: string
	/**
	 * C​o​n​t​e​x​t​ ​c​o​m​p​r​e​s​s​i​o​n​ ​o​r​ ​c​a​c​h​e​ ​e​v​e​n​t​s​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e
	 */
	memoryDebug_emptyHint: string
	/**
	 * C​l​e​a​r
	 */
	memoryDebug_clear: string
	/**
	 * C​o​m​p​r​e​s​s​i​o​n​ ​C​o​u​n​t
	 */
	memoryDebug_compressionCount: string
	/**
	 * A​v​g​ ​r​a​t​i​o​ ​{​0​}
	 * @param {string} 0
	 */
	memoryDebug_avgRatio: RequiredParams<'0'>
	/**
	 * C​o​m​p​r​e​s​s​i​o​n​ ​S​a​v​e​d
	 */
	memoryDebug_compressionSaved: string
	/**
	 * C​a​c​h​e​ ​H​i​t​s
	 */
	memoryDebug_cacheHitCount: string
	/**
	 * {​0​}​ ​h​i​t​s
	 * @param {string} 0
	 */
	memoryDebug_hitTimes: RequiredParams<'0'>
	/**
	 * E​v​e​n​t​ ​L​o​g​ ​(​{​0​}​)
	 * @param {string} 0
	 */
	memoryDebug_eventLog: RequiredParams<'0'>
	/**
	 * R​e​f​r​e​s​h​ ​d​i​r​e​c​t​o​r​y
	 */
	sidebar_refresh: string
	/**
	 * C​l​o​s​e​ ​d​i​r​e​c​t​o​r​y
	 */
	sidebar_closeDir: string
	/**
	 * S​k​i​l​l​s
	 */
	sidebar_skills: string
	/**
	 * U​s​e​r​ ​s​t​o​p​p​e​d​ ​e​x​e​c​u​t​i​o​n
	 */
	chat_userStopped: string
	/**
	 * E​x​e​c​u​t​i​o​n​ ​p​l​a​n​:​ ​{​0​}
	 * @param {string} 0
	 */
	chat_planExecution: RequiredParams<'0'>
	/**
	 * P​l​a​n​ ​g​e​n​e​r​a​t​i​o​n​ ​f​a​i​l​e​d​:​ ​{​0​}
	 * @param {string} 0
	 */
	chat_planFailed: RequiredParams<'0'>
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​t​i​m​e​d​ ​o​u​t​,​ ​f​a​i​l​e​d​ ​t​o​ ​e​s​t​a​b​l​i​s​h​ ​c​o​n​n​e​c​t​i​o​n​ ​t​o​ ​A​I​ ​s​e​r​v​i​c​e
	 */
	chat_connectionTimeout: string
	/**
	 * U​n​k​n​o​w​n​ ​e​r​r​o​r
	 */
	chat_unknownError: string
	/**
	 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
	 */
	error_unknown: string
	/**
	 * F​a​i​l​e​d​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​A​I​ ​p​r​o​v​i​d​e​r
	 */
	error_aiConnection: string
	/**
	 * C​a​n​n​o​t​ ​a​c​c​e​s​s​ ​f​i​l​e​ ​o​r​ ​d​i​r​e​c​t​o​r​y
	 */
	error_fileAccess: string
}

export type TranslationFunctions = {
	/**
	 * FileWork
	 */
	appName: () => LocalizedString
	/**
	 * Your Local File AI Assistant
	 */
	tagline: () => LocalizedString
	/**
	 * FileWork
	 */
	welcome_title: () => LocalizedString
	/**
	 * Your local file AI assistant. Select a working directory and tell me what to do.
	 */
	welcome_description: () => LocalizedString
	/**
	 * Select Working Directory
	 */
	welcome_selectDirectory: () => LocalizedString
	/**
	 * FileWork only works within your selected directory. Your data never leaves your computer.
	 */
	welcome_privacy: () => LocalizedString
	/**
	 * Tell me what you want to do... (⌘+Enter to send)
	 */
	chat_placeholder: () => LocalizedString
	/**
	 * How can I help?
	 */
	chat_emptyTitle: () => LocalizedString
	/**
	 * Tell me what you want to do with this directory
	 */
	chat_emptyDescription: () => LocalizedString
	/**
	 * Organize files in this directory by type
	 */
	suggestion_organize: () => LocalizedString
	/**
	 * Analyze this directory and generate a report
	 */
	suggestion_report: () => LocalizedString
	/**
	 * Find all duplicate files
	 */
	suggestion_duplicates: () => LocalizedString
	/**
	 * Count files by type and size
	 */
	suggestion_stats: () => LocalizedString
	/**
	 * Settings
	 */
	sidebar_settings: () => LocalizedString
	/**
	 * Collapse sidebar
	 */
	sidebar_collapse: () => LocalizedString
	/**
	 * Settings
	 */
	settings_title: () => LocalizedString
	/**
	 * AI Provider
	 */
	settings_aiProvider: () => LocalizedString
	/**
	 * API Key
	 */
	settings_apiKey: () => LocalizedString
	/**
	 * Model
	 */
	settings_model: () => LocalizedString
	/**
	 * Language
	 */
	settings_language: () => LocalizedString
	/**
	 * Theme
	 */
	settings_theme: () => LocalizedString
	/**
	 * Dark
	 */
	settings_themeDark: () => LocalizedString
	/**
	 * Light
	 */
	settings_themeLight: () => LocalizedString
	/**
	 * System
	 */
	settings_themeSystem: () => LocalizedString
	/**
	 * Test Connection
	 */
	settings_testConnection: () => LocalizedString
	/**
	 * Pending
	 */
	task_pending: () => LocalizedString
	/**
	 * Running
	 */
	task_running: () => LocalizedString
	/**
	 * Completed
	 */
	task_completed: () => LocalizedString
	/**
	 * Failed
	 */
	task_failed: () => LocalizedString
	/**
	 * Undo
	 */
	task_undo: () => LocalizedString
	/**
	 * LLM Channel Configuration
	 */
	llmConfig_title: () => LocalizedString
	/**
	 * Add Configuration
	 */
	llmConfig_add: () => LocalizedString
	/**
	 * Edit
	 */
	llmConfig_edit: () => LocalizedString
	/**
	 * Delete
	 */
	llmConfig_delete: () => LocalizedString
	/**
	 * Display Name
	 */
	llmConfig_name: () => LocalizedString
	/**
	 * Provider
	 */
	llmConfig_provider: () => LocalizedString
	/**
	 * API Key
	 */
	llmConfig_apiKey: () => LocalizedString
	/**
	 * Base URL
	 */
	llmConfig_baseUrl: () => LocalizedString
	/**
	 * Model
	 */
	llmConfig_model: () => LocalizedString
	/**
	 * Default
	 */
	llmConfig_default: () => LocalizedString
	/**
	 * Set as Default
	 */
	llmConfig_setDefault: () => LocalizedString
	/**
	 * Are you sure you want to delete this configuration?
	 */
	llmConfig_deleteConfirm: () => LocalizedString
	/**
	 * At least one default configuration must be kept
	 */
	llmConfig_deleteLastError: () => LocalizedString
	/**
	 * This field is required
	 */
	llmConfig_validationRequired: () => LocalizedString
	/**
	 * API Key is invalid or expired, please check the channel configuration in settings
	 */
	llmConfig_authError: () => LocalizedString
	/**
	 * Selected LLM configuration does not exist
	 */
	llmConfig_notFound: () => LocalizedString
	/**
	 * Save
	 */
	llmConfig_save: () => LocalizedString
	/**
	 * Cancel
	 */
	llmConfig_cancel: () => LocalizedString
	/**
	 * Recently Opened
	 */
	welcome_recentlyOpened: () => LocalizedString
	/**
	 * Remove
	 */
	welcome_remove: () => LocalizedString
	/**
	 * Chat History
	 */
	session_history: () => LocalizedString
	/**
	 * Close
	 */
	session_close: () => LocalizedString
	/**
	 * No chat history
	 */
	session_empty: () => LocalizedString
	/**
	 * Delete chat
	 */
	session_delete: () => LocalizedString
	/**
	 * New Chat
	 */
	session_newChat: () => LocalizedString
	/**
	 * Reject
	 */
	chat_reject: () => LocalizedString
	/**
	 * Approve
	 */
	chat_approve: () => LocalizedString
	/**
	 * Approved
	 */
	chat_approved: () => LocalizedString
	/**
	 * Rejected
	 */
	chat_rejected: () => LocalizedString
	/**
	 * Error
	 */
	chat_error: () => LocalizedString
	/**
	 * Retrying ({0}/{1})...
	 */
	chat_retrying: (arg0: string, arg1: string) => LocalizedString
	/**
	 * Analyzing task, generating plan...
	 */
	chat_planGenerating: () => LocalizedString
	/**
	 * Thinking...
	 */
	chat_thinking: () => LocalizedString
	/**
	 * Fork from here
	 */
	chat_forkHere: () => LocalizedString
	/**
	 * Tell me what you want to do... (Enter to send)
	 */
	chat_inputPlaceholder: () => LocalizedString
	/**
	 * Auth Failed
	 */
	errorType_auth: () => LocalizedString
	/**
	 * API key is invalid or expired, please check configuration in settings
	 */
	errorType_authHint: () => LocalizedString
	/**
	 * Insufficient Balance
	 */
	errorType_billing: () => LocalizedString
	/**
	 * API account balance insufficient, please top up on the provider platform
	 */
	errorType_billingHint: () => LocalizedString
	/**
	 * Rate Limited
	 */
	errorType_rateLimit: () => LocalizedString
	/**
	 * Request rate too high, auto-retried but still failed
	 */
	errorType_rateLimitHint: () => LocalizedString
	/**
	 * Context Too Long
	 */
	errorType_contextOverflow: () => LocalizedString
	/**
	 * Conversation too long, please start a new chat
	 */
	errorType_contextOverflowHint: () => LocalizedString
	/**
	 * Service Unavailable
	 */
	errorType_serverError: () => LocalizedString
	/**
	 * Server temporarily unavailable, please try again later
	 */
	errorType_serverErrorHint: () => LocalizedString
	/**
	 * Request Timeout
	 */
	errorType_timeout: () => LocalizedString
	/**
	 * Connection timed out, please try again later
	 */
	errorType_timeoutHint: () => LocalizedString
	/**
	 * Network Blocked
	 */
	errorType_proxyIntercepted: () => LocalizedString
	/**
	 * Request blocked by proxy or firewall, please check network settings
	 */
	errorType_proxyInterceptedHint: () => LocalizedString
	/**
	 * Rate Limit
	 */
	retry_rateLimit: () => LocalizedString
	/**
	 * Context Compression
	 */
	retry_contextOverflow: () => LocalizedString
	/**
	 * Server Error
	 */
	retry_serverError: () => LocalizedString
	/**
	 * Connection Timeout
	 */
	retry_timeout: () => LocalizedString
	/**
	 * Retry
	 */
	recovery_retry: () => LocalizedString
	/**
	 * Check Settings
	 */
	recovery_settings: () => LocalizedString
	/**
	 * New Chat
	 */
	recovery_newChat: () => LocalizedString
	/**
	 * Preparing
	 */
	tool_preparing: () => LocalizedString
	/**
	 * Running
	 */
	tool_running: () => LocalizedString
	/**
	 * Done
	 */
	tool_done: () => LocalizedString
	/**
	 * Error
	 */
	tool_error: () => LocalizedString
	/**
	 * Parameters
	 */
	tool_params: () => LocalizedString
	/**
	 * Result
	 */
	tool_result: () => LocalizedString
	/**
	 * Error
	 */
	tool_errorLabel: () => LocalizedString
	/**
	 * List Directory
	 */
	toolName_listDirectory: () => LocalizedString
	/**
	 * Read File
	 */
	toolName_readFile: () => LocalizedString
	/**
	 * Write File
	 */
	toolName_writeFile: () => LocalizedString
	/**
	 * Move File
	 */
	toolName_moveFile: () => LocalizedString
	/**
	 * Create Directory
	 */
	toolName_createDirectory: () => LocalizedString
	/**
	 * Delete File
	 */
	toolName_deleteFile: () => LocalizedString
	/**
	 * Directory Stats
	 */
	toolName_directoryStats: () => LocalizedString
	/**
	 * Find Duplicates
	 */
	toolName_findDuplicates: () => LocalizedString
	/**
	 * Run Command
	 */
	toolName_runCommand: () => LocalizedString
	/**
	 * Execution Plan
	 */
	plan_title: () => LocalizedString
	/**
	 * Slow Response
	 */
	plan_stalled: () => LocalizedString
	/**
	 * Artifacts ({0})
	 */
	plan_artifacts: (arg0: string) => LocalizedString
	/**
	 * Reject
	 */
	plan_reject: () => LocalizedString
	/**
	 * Start Execution
	 */
	plan_start: () => LocalizedString
	/**
	 * Cancel Execution
	 */
	plan_cancel: () => LocalizedString
	/**
	 * Plan completed
	 */
	plan_completed: () => LocalizedString
	/**
	 * Plan failed
	 */
	plan_failed: () => LocalizedString
	/**
	 * Plan cancelled
	 */
	plan_cancelled: () => LocalizedString
	/**
	 * Error: {0}
	 */
	plan_stepError: (arg0: string) => LocalizedString
	/**
	 * Scroll to bottom
	 */
	conv_scrollToBottom: () => LocalizedString
	/**
	 * New messages
	 */
	conv_newMessages: () => LocalizedString
	/**
	 * User
	 */
	conv_roleUser: () => LocalizedString
	/**
	 * Assistant
	 */
	conv_roleAssistant: () => LocalizedString
	/**
	 * Download conversation
	 */
	conv_download: () => LocalizedString
	/**
	 * Close preview
	 */
	preview_close: () => LocalizedString
	/**
	 * Loading file...
	 */
	preview_loading: () => LocalizedString
	/**
	 * Preview not supported for
	 */
	preview_unsupported: () => LocalizedString
	/**
	 * this type
	 */
	preview_unsupportedType: () => LocalizedString
	/**
	 * files
	 */
	preview_files: () => LocalizedString
	/**
	 * Zoom in
	 */
	preview_zoomIn: () => LocalizedString
	/**
	 * Zoom out
	 */
	preview_zoomOut: () => LocalizedString
	/**
	 * Failed to read image
	 */
	preview_readImageError: () => LocalizedString
	/**
	 * Failed to read file
	 */
	preview_readFileError: () => LocalizedString
	/**
	 * Unable to play this video file
	 */
	preview_videoError: () => LocalizedString
	/**
	 * Video preview: {0}
	 */
	preview_videoLabel: (arg0: string) => LocalizedString
	/**
	 * Loading...
	 */
	code_loading: () => LocalizedString
	/**
	 * Loading skills...
	 */
	skill_loading: () => LocalizedString
	/**
	 * No skills matching "{0}"
	 */
	skill_notFound: (arg0: string) => LocalizedString
	/**
	 * Type skill name to search
	 */
	skill_searchHint: () => LocalizedString
	/**
	 * Skill Approval Request
	 */
	skillApproval_title: () => LocalizedString
	/**
	 * Skill Name:
	 */
	skillApproval_name: () => LocalizedString
	/**
	 * Source Path:
	 */
	skillApproval_source: () => LocalizedString
	/**
	 * Commands to execute:
	 */
	skillApproval_commands: () => LocalizedString
	/**
	 * Hook scripts:
	 */
	skillApproval_hooks: () => LocalizedString
	/**
	 * Reject
	 */
	skillApproval_reject: () => LocalizedString
	/**
	 * Approve
	 */
	skillApproval_approve: () => LocalizedString
	/**
	 * Skill Manager
	 */
	skillsModal_title: () => LocalizedString
	/**
	 * Search skills...
	 */
	skillsModal_search: () => LocalizedString
	/**
	 * All ({0})
	 */
	skillsModal_all: (arg0: string) => LocalizedString
	/**
	 * No matching skills found
	 */
	skillsModal_notFound: () => LocalizedString
	/**
	 * Task
	 */
	skillsModal_task: () => LocalizedString
	/**
	 * Tool
	 */
	skillsModal_tool: () => LocalizedString
	/**
	 * Auto Match
	 */
	skillsModal_autoMatch: () => LocalizedString
	/**
	 * Loading...
	 */
	skillsModal_loading: () => LocalizedString
	/**
	 * Skill info not found
	 */
	skillsModal_notFoundInfo: () => LocalizedString
	/**
	 * Task Type
	 */
	skillsModal_taskType: () => LocalizedString
	/**
	 * Tool Type
	 */
	skillsModal_toolType: () => LocalizedString
	/**
	 * Isolated Context
	 */
	skillsModal_isolatedContext: () => LocalizedString
	/**
	 * Manual Trigger Only
	 */
	skillsModal_manualOnly: () => LocalizedString
	/**
	 * Description
	 */
	skillsModal_description: () => LocalizedString
	/**
	 * Usage
	 */
	skillsModal_usage: () => LocalizedString
	/**
	 * /{0} <your instruction>
	 */
	skillsModal_usageCommand: (arg0: string) => LocalizedString
	/**
	 * Just describe your needs in the conversation, AI will auto-match this skill by keywords.
	 */
	skillsModal_usageAuto: () => LocalizedString
	/**
	 * Suggested Prompts
	 */
	skillsModal_suggestions: () => LocalizedString
	/**
	 * Keywords
	 */
	skillsModal_keywords: () => LocalizedString
	/**
	 * Source Path
	 */
	skillsModal_sourcePath: () => LocalizedString
	/**
	 * Show in Finder
	 */
	skillsModal_showInFinder: () => LocalizedString
	/**
	 * Allowed Tools
	 */
	skillsModal_allowedTools: () => LocalizedString
	/**
	 * Dependencies
	 */
	skillsModal_dependencies: () => LocalizedString
	/**
	 * Command
	 */
	skillsModal_depCommand: () => LocalizedString
	/**
	 * Environment Variable
	 */
	skillsModal_depEnvVar: () => LocalizedString
	/**
	 * System
	 */
	skillsModal_depSystem: () => LocalizedString
	/**
	 * Lifecycle
	 */
	skillsModal_lifecycle: () => LocalizedString
	/**
	 * This skill includes pre-activate / post-complete hook scripts
	 */
	skillsModal_lifecycleHint: () => LocalizedString
	/**
	 * Built-in
	 */
	skillsModal_sourceBuiltIn: () => LocalizedString
	/**
	 * Project
	 */
	skillsModal_sourceProject: () => LocalizedString
	/**
	 * Personal
	 */
	skillsModal_sourcePersonal: () => LocalizedString
	/**
	 * Additional
	 */
	skillsModal_sourceAdditional: () => LocalizedString
	/**
	 * Loading usage data...
	 */
	usage_loading: () => LocalizedString
	/**
	 * No usage data yet
	 */
	usage_empty: () => LocalizedString
	/**
	 * Token Usage Statistics
	 */
	usage_title: () => LocalizedString
	/**
	 * Total
	 */
	usage_total: () => LocalizedString
	/**
	 * Input
	 */
	usage_input: () => LocalizedString
	/**
	 * Output
	 */
	usage_output: () => LocalizedString
	/**
	 * By Model
	 */
	usage_byModel: () => LocalizedString
	/**
	 * ({0} tasks)
	 */
	usage_tasks: (arg0: string) => LocalizedString
	/**
	 * Recent Usage
	 */
	usage_recent: () => LocalizedString
	/**
	 * Context Compression
	 */
	memoryDebug_contextCompression: () => LocalizedString
	/**
	 * Compression Skipped
	 */
	memoryDebug_compressionSkipped: () => LocalizedString
	/**
	 * Cache Write
	 */
	memoryDebug_cacheWrite: () => LocalizedString
	/**
	 * Cache Hit
	 */
	memoryDebug_cacheHit: () => LocalizedString
	/**
	 * ({0} messages)
	 */
	memoryDebug_messagesCompressed: (arg0: string) => LocalizedString
	/**
	 * (not over limit)
	 */
	memoryDebug_notOverLimit: () => LocalizedString
	/**
	 * Wrote {0} tokens
	 */
	memoryDebug_cacheWriteTokens: (arg0: string) => LocalizedString
	/**
	 * Hit {0} tokens
	 */
	memoryDebug_cacheReadTokens: (arg0: string) => LocalizedString
	/**
	 * Loading debug data...
	 */
	memoryDebug_loading: () => LocalizedString
	/**
	 * No Memory events yet
	 */
	memoryDebug_empty: () => LocalizedString
	/**
	 * Context compression or cache events will appear here
	 */
	memoryDebug_emptyHint: () => LocalizedString
	/**
	 * Clear
	 */
	memoryDebug_clear: () => LocalizedString
	/**
	 * Compression Count
	 */
	memoryDebug_compressionCount: () => LocalizedString
	/**
	 * Avg ratio {0}
	 */
	memoryDebug_avgRatio: (arg0: string) => LocalizedString
	/**
	 * Compression Saved
	 */
	memoryDebug_compressionSaved: () => LocalizedString
	/**
	 * Cache Hits
	 */
	memoryDebug_cacheHitCount: () => LocalizedString
	/**
	 * {0} hits
	 */
	memoryDebug_hitTimes: (arg0: string) => LocalizedString
	/**
	 * Event Log ({0})
	 */
	memoryDebug_eventLog: (arg0: string) => LocalizedString
	/**
	 * Refresh directory
	 */
	sidebar_refresh: () => LocalizedString
	/**
	 * Close directory
	 */
	sidebar_closeDir: () => LocalizedString
	/**
	 * Skills
	 */
	sidebar_skills: () => LocalizedString
	/**
	 * User stopped execution
	 */
	chat_userStopped: () => LocalizedString
	/**
	 * Execution plan: {0}
	 */
	chat_planExecution: (arg0: string) => LocalizedString
	/**
	 * Plan generation failed: {0}
	 */
	chat_planFailed: (arg0: string) => LocalizedString
	/**
	 * Connection timed out, failed to establish connection to AI service
	 */
	chat_connectionTimeout: () => LocalizedString
	/**
	 * Unknown error
	 */
	chat_unknownError: () => LocalizedString
	/**
	 * An unknown error occurred
	 */
	error_unknown: () => LocalizedString
	/**
	 * Failed to connect to AI provider
	 */
	error_aiConnection: () => LocalizedString
	/**
	 * Cannot access file or directory
	 */
	error_fileAccess: () => LocalizedString
}

export type Formatters = {}
