/**
 * `requestDesignApproval` — the brainstorming HARD-GATE handoff tool.
 *
 * The brainstorming process skill instructs the agent to call this
 * tool with a complete design markdown BEFORE making any destructive
 * tool calls. Execution:
 *
 *   1. Records the pending design in `chat-workflow-state` (keyed by
 *      sessionId-or-taskId), keeping `designApproved: false` until the
 *      user explicitly approves.
 *   2. Emits an IPC `ai:stream-design-approval` event the renderer
 *      can use to surface an inline approval card.
 *   3. Returns `{ pending: true, message }` so the agent loop ends the
 *      current turn — it must wait for the user's decision before
 *      attempting any destructive tool call.
 *
 * The companion `chat:design-decision` IPC handler (renderer → main)
 * is responsible for flipping `designApproved` once the user clicks
 * Approve / Reject.
 */

import type { WebContents } from "electron";
import { z } from "zod/v4";

import {
  recordPendingDesign,
  resolveWorkflowKey,
} from "../../../state/chat-workflow-state";
import type { ToolDefinition } from "../tool-registry";

export interface RequestDesignApprovalDeps {
  sender: WebContents;
  /** Per-task UUID generated by `handleTaskExecution`. */
  taskId: string;
  /** Chat-session id (preferred workflow key). Undefined for one-shot. */
  sessionId?: string;
}

interface RequestDesignApprovalArgs {
  /** The full design markdown to be approved. */
  design: string;
  /** Optional 1-line headline shown above the design in the UI card. */
  summary?: string;
}

interface RequestDesignApprovalResult {
  pending: true;
  message: string;
}

export const buildRequestDesignApprovalTool = ({
  sender,
  taskId,
  sessionId,
}: RequestDesignApprovalDeps): ToolDefinition<
  RequestDesignApprovalArgs,
  RequestDesignApprovalResult
> => ({
  name: "requestDesignApproval",
  description:
    "Send the user a proposed design and pause the agent until the user approves or rejects it. Call this BEFORE any destructive tool (writeFile, deleteFile, runCommand, git*, github*, gitlab*) on creative tasks. The agent must STOP after this tool returns and wait for the user's reply.",
  safety: "safe",
  inputSchema: z.object({
    design: z
      .string()
      .min(1)
      .describe(
        "The full design markdown — scope, files to touch, approach, verification. Scale length to task complexity.",
      ),
    summary: z
      .string()
      .optional()
      .describe(
        "Optional one-line headline (≤ 80 chars) shown above the design.",
      ),
  }),
  execute: async ({ design, summary }) => {
    const workflowKey = resolveWorkflowKey(sessionId, taskId);
    recordPendingDesign(workflowKey, design);

    if (!sender.isDestroyed()) {
      sender.send("ai:stream-design-approval", {
        id: taskId,
        workflowKey,
        design,
        summary,
      });
    }

    return {
      pending: true,
      message:
        "Design sent to the user for approval. Stop now and wait — do not call any destructive tool until the user replies with an Approve decision. If they Reject, revise the design and call this tool again.",
    };
  },
});
