import type { TranslationFunctions } from "../../i18n/i18n-types";

/** Human-readable tool name labels (shared between tool.tsx and plan-viewer.tsx) */
export const getToolLabels = (
  LL: TranslationFunctions,
): Record<string, string> => ({
  listDirectory: LL.toolName_listDirectory(),
  readFile: LL.toolName_readFile(),
  writeFile: LL.toolName_writeFile(),
  moveFile: LL.toolName_moveFile(),
  createDirectory: LL.toolName_createDirectory(),
  deleteFile: LL.toolName_deleteFile(),
  directoryStats: LL.toolName_directoryStats(),
  findDuplicates: LL.toolName_findDuplicates(),
  searchFiles: LL.toolName_searchFiles(),
  automation_update: LL.toolName_automationUpdate(),
  runCommand: LL.toolName_runCommand(),
  runProcess: LL.toolName_runProcess(),
  webSearch: LL.toolName_webSearch(),
  webFetch: LL.toolName_webFetch(),
  webFetchRendered: LL.toolName_webFetchRendered(),
  webScrape: LL.toolName_webScrape(),
  browserOpen: LL.toolName_browserOpen(),
  browserTabs: LL.toolName_browserTabs(),
  browserSwitchTab: LL.toolName_browserSwitchTab(),
  browserSnapshot: LL.toolName_browserSnapshot(),
  browserClick: LL.toolName_browserClick(),
  browserType: LL.toolName_browserType(),
  browserPress: LL.toolName_browserPress(),
  browserScroll: LL.toolName_browserScroll(),
  browserClose: LL.toolName_browserClose(),
  youtubeTranscript: LL.toolName_youtubeTranscript(),
  spawnSubagent: LL.toolName_spawnSubagent(),
  submitSubagentResult: LL.toolName_submitSubagentResult(),
});
