/** Planner types — shared between planner, executor, and IPC layer. */

export interface PlanSubStep {
  /** Short label describing a concrete action within the parent step */
  label: string;
  /** Whether this sub-step has been completed */
  status: "pending" | "done";
}

export interface PlanStep {
  /** Sequential step id (1-based) */
  id: number;
  /** Short action label (e.g. "scan", "organize", "report") */
  action: string;
  /** Human-readable description of what this step does */
  description: string;
  /** Optional skill id to activate for this step */
  skillId?: string;
  /** Breakdown of concrete actions within this step */
  subSteps?: PlanSubStep[];
  /** Execution status */
  status: "pending" | "running" | "completed" | "failed" | "skipped";
  /** Result summary after execution (brief, for context passing) */
  resultSummary?: string;
  /** Error message if failed */
  error?: string;
}

export interface Plan {
  /** Unique plan id */
  id: string;
  /** The original user prompt */
  prompt: string;
  /** High-level goal description generated by the planner */
  goal: string;
  /** Ordered list of steps */
  steps: PlanStep[];
  /** Overall plan status */
  status:
    | "draft"
    | "approved"
    | "executing"
    | "completed"
    | "failed"
    | "cancelled";
  /** Workspace path */
  workspacePath: string;
  /** ISO timestamp */
  createdAt: string;
  /** ISO timestamp */
  updatedAt: string;
}

/**
 * The structured JSON the LLM is expected to output during the plan phase.
 * This is a subset of Plan — we fill in the rest ourselves.
 */
export interface PlannerLLMOutput {
  goal: string;
  steps: Array<{
    action: string;
    description: string;
    skillId?: string;
    subSteps?: string[];
  }>;
}
