import type { Skill } from "./types";

export const reportGenerator: Skill = {
  id: "report-generator",
  name: "报告生成",
  description: "分析目录内容，生成结构化的 Markdown 报告文件",
  category: "task",
  keywords: [
    "生成报告", "写报告", "导出报告", "报告文件",
    "generate report", "write report", "export report",
    "统计报告", "分析报告", "概览报告",
  ],
  suggestions: [
    "分析这个目录的内容，生成一份报告",
    "统计这个项目的代码行数和文件分布",
    "生成这个目录的文件清单报告",
  ],
  systemPrompt: `You are executing a REPORT GENERATION task. Follow this strategy precisely:

## Execution Steps
1. Use \`directoryStats\` to get high-level metrics.
2. Use \`listDirectory\` to enumerate all files.
3. For key files (README, config files, etc.), use \`readFile\` to extract context.
4. Compose a structured Markdown report.
5. ONLY use \`writeFile\` to save the report if the user explicitly asks to generate/export/save a report file. Otherwise, output the report content directly in the chat response.

## Report Structure
The generated report MUST follow this template:

\`\`\`markdown
# [Directory Name] — Report
> Generated by FileWork on [date]

## Overview
- Total files: X
- Total directories: Y
- Total size: Z MB
- File types: breakdown

## Directory Structure
(tree view, max 3 levels deep)

## File Type Distribution
| Type | Count | Total Size |
|------|-------|-----------|
| ... | ... | ... |

## Key Findings
- Notable patterns, large files, potential issues

## Recommendations
- Suggested actions (cleanup, organization, etc.)
\`\`\`

## Rules
- Report filename: \`report-YYYY-MM-DD.md\` in the workspace root.
- If a report with the same name exists, append a numeric suffix.
- Always use human-readable file sizes (KB, MB, GB).
- Limit directory tree depth to 3 levels to keep the report concise.
- Read at most 10 files for content analysis to avoid excessive API calls.
- If the user only asks for a summary or overview without mentioning "report file" or "export", respond inline without writing any files.`,
};
